theme = "ananke"
languageCode = "en-us"
title = "CynosurePalace"
baseURL = "https://ChenGou-zheng.github.io/" 

[params]
  description = "Your time is limited, so don’t waste it living someone else’s life."
  author = "ChenGou"
  avatar = "/avatarMe.png"  # 放在 static/ 下
  socialIcons = true

[params.social]
  github = "https://github.com/ChenGou-zheng" 
  qq = "1339495928" 
  email = "12412903@mail.sustech.edu.cn"

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "博客"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "总结"
    url = "/summaries/"
    weight = 3
  [[menu.main]]
    name = "笔记"
    url = "/notes/"
    weight = 4
  [[menu.main]]
    name = "AI"
    url = "/ai/"
    weight = 5
  [[menu.main]]
    name = "机器人"
    url = "/robot/"
    weight = 6
  [[menu.main]]
    name = "工具"
    url = "/tools/"
    weight = 7
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 8