theme = "ananke"
languageCode = "en-us"
title = "CynosurePalace"
baseURL = "https://ChenGou-zheng.github.io/" 

[params]
  description = "Your time is limited, so don’t waste it living someone else’s life."
  author = "ChenGou"
  avatar = "/avatarMe.png"  # 放在 static/ 下
  socialIcons = true

[params.social]
  github = "https://github.com/ChenGou-zheng" 
  qq = "1339495928" 
  email = "12412903@mail.sustech.edu.cn"

[menu]
[[menu.main]]
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  name = "工具"
  url = "/tools/"
  weight = 7

[[menu.main]]
  name = "CynosurePalace"
  url = "/cynosurepalace/"
  weight = 99

[[menu.main]]
  name = "Lectures"
  url = "/lectures/"
  weight = 99