name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # 如果您的主分支是 main，请改为 main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest' # 使用 'latest' 或一个已知的有效版本
          extended: true

      - name: Build website
        # 核心修正：保留 --source 参数，但移除错误的 --destination。
        # Hugo 会在项目根目录创建一个 ./public 文件夹来存放结果。
        run: hugo --source hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # 这个路径现在也是正确的
          publish_branch: gh-pages