# 为您的 Hugo 网站构建和部署的 GitHub Actions 工作流

name: Build and Deploy Hugo Site

# 触发条件：当有代码 push 到 master 分支时自动运行
on:
  push:
    branches:
      - master

# 作业流程
jobs:
  deploy:
    # 指定运行此作业的操作系统
    runs-on: ubuntu-latest
    # 授予工作流写入仓库内容的权限
    permissions:
      contents: write

    steps:
      # 第 1 步：检出（Checkout）您的源码
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true

      # 第 2 步：安装 Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # 第 3 步：构建网站
      - name: Build website
        # 核心修正：使用 --source 参数告诉 Hugo 源文件的位置在 'hugo' 文件夹
        run: hugo --source hugo --minify

      # 第 4 步：部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Hugo 构建的结果依然会输出到根目录的 public 文件夹
          publish_branch: gh-pages