# 为您的 Hugo 网站构建和部署的 GitHub Actions 工作流 (包含调试步骤)

name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 第 1 步：检出源码
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true

      # 第 2 步：安装 Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # 第 3 步：构建网站
      - name: Build website
        run: hugo --source hugo --minify

      # 第 4 步：【侦探步骤】检查并列出构建结果
      - name: Check build output
        run: |
          echo "--- Checking contents of ./public directory ---"
          if [ -d "public" ] && [ "$(ls -A public)" ]; then
            ls -R public
          else
            echo "!!! CRITICAL: Build failed. The './public' directory is empty or does not exist."
            exit 1
          fi
          echo "-------------------------------------------------"

      # 第 5 步：部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages